// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgaI9eI08Mi9gyRds7nModCJlSsUTXP2E',
    appId: '1:845417072769:android:02f733237f9945ad78a580',
    messagingSenderId: '845417072769',
    projectId: 'chatapp-c46f3',
    databaseURL: 'https://chatapp-c46f3-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-c46f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXD6CHU0pzv2NvlmhLbKMzYOBTsaXHYTA',
    appId: '1:845417072769:ios:fe0f0a88d4dc715978a580',
    messagingSenderId: '845417072769',
    projectId: 'chatapp-c46f3',
    databaseURL: 'https://chatapp-c46f3-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-c46f3.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );
}
